name: Run test in docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    IMAGE_NAME: i_hate_typescript
    CONTAINER_NAME: i_hate_typescript_container
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t i_hate_typescript

    - name: Run the container
      run: docker run --memory 4g --name $CONTAINER_NAME $IMAGE_NAME
